#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'lab3' in
 * file './lab3.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'vga_led_0', class 'vga_led'
 * The macros are prefixed with 'IK_DRIVER_0_'.
 * The prefix is the slave descriptor.
 */
#define IK_DRIVER_0_COMPONENT_TYPE ik_driver
#define IK_DRIVER_0_COMPONENT_NAME ik_driver_0
#define IK_DRIVER_0_BASE 0x0
#define IK_DRIVER_0_SPAN 8
#define IK_DRIVER_0_END 0x7


#endif /* _ALTERA_HPS_0_H_ */
